// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module('selectAddress', []);

  app.directive('selectAddress', function($http, $q, $compile) {
    var delay, isInit;
    isInit = false;
    delay = $q.defer();
    return {
      restrict: 'A',
      scope: {
        p: '=',
        a: '=',
        c: '=',
        d: '='
      },
      link: function(scope, element, attrs) {
        var popup;
        if (!isInit) {
          isInit = true;
          $http.get('template/index.html').success(function(data) {
            $('body').append($compile(data)(scope));
            return $http.get("template/city.min.js").success(function(data) {
              scope.provinces = data;
              delay.resolve(scope.provinces);
              return popup.init();
            });
          });
        }
        popup = {
          show: function() {
            return $('.select-address').addClass('active');
          },
          hide: function() {
            $('.select-address').removeClass('active');
            return false;
          },
          resize: function() {
            var $template;
            $template = $('.select-address');
            $template.on('click', function() {
              return event.stopPropagation();
            }).show().css({
              top: -$template.height() - 30,
              'margin-left': -$template.width() / 2
            });
            return false;
          },
          focus: function() {
            $('[ng-model="d"]').focus();
            return false;
          },
          init: function() {
            return $(window).on('click', (function(_this) {
              return function() {
                return _this.hide();
              };
            })(this));
          }
        };
        return delay.promise.then(function(data) {
          element.on('click', function() {
            event.stopPropagation();
            return $('.select-address').addClass('active');
          });
          scope.aSet = {
            p: function(p) {
              scope.p = p;
              scope.c = null;
              scope.a = null;
              return scope.d = null;
            },
            c: function(c) {
              scope.c = c;
              scope.a = null;
              return scope.d = null;
            },
            a: function(a) {
              scope.a = a;
              scope.d = null;
              return popup.focus();
            }
          };
          scope.clear = function() {
            scope.p = null;
            scope.c = null;
            scope.a = null;
            return scope.d = null;
          };
          scope.submit = function() {
            return popup.hide();
          };
          scope.$watch('p', function(newV) {
            var v, _i, _len, _results;
            if (newV) {
              _results = [];
              for (_i = 0, _len = data.length; _i < _len; _i++) {
                v = data[_i];
                if (v.p === newV) {
                  _results.push(scope.cities = v.c);
                }
              }
              return _results;
            } else {
              return scope.cities = [];
            }
          });
          scope.$watch('c', function(newV) {
            var v, _i, _len, _ref, _results;
            if (newV) {
              _ref = scope.cities;
              _results = [];
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                v = _ref[_i];
                if (v.n === newV) {
                  _results.push(scope.dists = v.a);
                }
              }
              return _results;
            } else {
              return scope.dists = [];
            }
          });
          return scope.$watch(function() {
            return popup.resize();
          });
        });
      }
    };
  });

}).call(this);

//# sourceMappingURL=selectAddress2.map
